use_frameworks!

source 'https://github.com/yangguang521/HFTotalPrivateSpec.git'

platform :ios, '10.0'

target 'HFFileManger_Example' do
  pod 'HFFileManger', :path => '../'

  target 'HFFileManger_Tests' do
    inherit! :search_paths

  end
end
